### ISSUE TITLE
Manufacturing & Inventory & API

### ISSUE THREAD

**Issue by hecko** [mpkasp/indabom#25]
Hi Mike,
we are looking for a simple Django-based tool to manage our BOMs, however I have a few questions to ask as there is very limited documentation here:

1) Is there a possibility to create a super-easy inventory interface? That is - upload a delivery note (in CSV lets say) and have the inventory of parts updated in terms how many units of each pars are available in stock?

2) Is there a way to create a "manufacturing order" - that is - lets say we have this product which contains 300+ electronic parts including plastic parts and sub assemblies etc - is there a way to klick "Im now making 100 units of this product" and Idabom will check which parts are in stock, which need to be bought or 3d printed / manufactured ...

Doing this using API would be absolutely awesome since we can integrate this with KiCad and some other applications to have a working inventory systems for KiCad assemblies and parent products.

I have more ideas here, but really cannot contribute time to this. Thigs like variations of the same product and its different BOMs etc.

**Comment by mpkasp** [comment]
1. Some simple inventory management has been discussed [here](https://github.com/mpkasp/django-bom/issues/12). I like the idea of adding the ability to upload a CSV to update part stock.
2. This sounds great. I've thought about something like this too but dont have an issue - just created one to track [here](https://github.com/mpkasp/django-bom/issues/70).

Yes it's been hard for me to add new features to the tool recently due to life, but hope to track some of these great ideas and add to the tool in the near future unless someone can help get to them first.

I'll be closing this ticket as these comments are for the [django-bom](https://github.com/mpkasp/django-bom) package.
